[[constraint]]
  branch = "v1"
  name = "github.com/Masterminds/squirrel"

[[constraint]]
  branch = "master"
  name = "github.com/Shopify/go-dogstatsd"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/shopspring/decimal"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/siddontang/go-mysql"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/golang/snappy"
  revision = "2e65f85255dbc3072edf28d6b5b8efc472979f5a"

[prune]
  go-tests = true
  unused-packages = true
